#!/bin/bash
read -n 1 -s -r -p "Переместите бинарный файл программы в папку, где находится скрипт, и нажмите любую клавишу..."

sudo cp ./applications/ds9.desktop /usr/share/applications/
sudo cp ./pixmaps/ds9.png /usr/share/pixmaps/ds9.png
sudo mv ./ds9 /usr/bin/ds9

echo 'Не забудьте перенести исполняемый бинарный файл в папку /usr/bin, если вы не поместили его перед установкой в эту папку. Возможно придется перезагрузить компьютер!'
$SHELL

